SELECT EMAIL,
    MAX(CPF) AS CPF,
    MAX(PRIMEIRO_NOME) AS PRIMEIRO_NOME,
    MAX(SOBRENOME) AS SOBRENOME,
    MAX(GENERO) AS GENERO,
    MAX(Data_NASCIMENTO) AS Data_NASCIMENTO,
    MAX(IDADE) AS IDADE,
    MAX(CIDADE) AS CIDADE,
FROM DE
WHERE EMAIL IS NOT NULL
AND GENERO like '%M%'
GROUP BY EMAIL
